.github/workflows/master.yml, .github/workflows/thriftserver.yml
This pr disable fail-fast for Github action.
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
No.
=> [MINOR][INFRA] Disable fail-fast for Github action

.github/workflows/master.yml
This pr fix ./dev/lint-java.
N/A
=> [MINOR] Fix ./dev/lint-java

sql/jdbc/src/main/java/org/apache/spark/sql/jdbc/JdbcColumn.java, sql/jdbc/src/main/java/org/apache/spark/sql/jdbc/SparkBaseResultSet.java, sql/jdbc/src/test/scala/org/apache/spark/sql/jdbc/SparkThriftServer2Suites.scala, sql/service/if/TCLIService.thrift, sql/service/src/gen/thrift/gen-javabean/org/apache/spark/sql/service/rpc/thrift/TCLIServiceConstants.java, sql/service/src/gen/thrift/gen-javabean/org/apache/spark/sql/service/rpc/thrift/TTypeId.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/ColumnValue.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/Type.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/TypeDescriptor.java, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/SparkExecuteStatementOperation.scala, sql/service/src/test/scala/org/apache/spark/sql/service/SparkExecuteStatementOperationSuite.scala
This PR makes new thrift server support `CalendarIntervalType` and `NullType `.
Unit test
=> Support CalendarIntervalType and NullType

sql/service/src/main/java/org/apache/spark/sql/service/cli/session/ServiceSessionImpl.java, sql/service/src/main/java/org/apache/spark/sql/service/utils/SystemVariables.java
This PR add support `--hiveconf` and `--hivevar`.
=> Support --hiveconf and --hivevar

sql/jdbc/src/test/scala/org/apache/spark/sql/jdbc/SparkThriftServer2Suites.scala, sql/service/src/main/java/org/apache/spark/sql/service/cli/session/SessionManager.java, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/OperationManager.scala, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/SparkExecuteStatementOperation.scala, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/SparkGetCatalogsOperation.scala, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/SparkGetColumnsOperation.scala, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/SparkGetFunctionsOperation.scala, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/SparkGetSchemasOperation.scala, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/SparkGetTableTypesOperation.scala, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/SparkGetTablesOperation.scala, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/SparkGetTypeInfoOperation.scala, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/SparkMetadataOperation.scala, sql/service/src/main/scala/org/apache/spark/sql/service/cli/session/SparkSQLSessionManager.scala
=> [WIP] Replace spark operation's  SQLContext

sql/service/src/main/java/org/apache/spark/sql/service/cli/session/ServiceSessionBase.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/session/ServiceSessionImpl.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/session/SessionManager.java
Replace sessionConf and sessionVariable by sqlContext
=> Replace sessionConf and sessionVariable by sqlContext

sql/service/src/main/java/org/apache/spark/sql/service/cli/session/ServiceSessionBase.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/session/SessionManager.java
=> Remove unused import

sql/service/src/main/java/org/apache/spark/sql/service/cli/operation/OperationLog.java, sql/service/src/main/java/org/apache/spark/sql/service/utils/SystemVariables.java
=> Revert "remove common.log deps (#22)" and fix lint-java

sql/service/pom.xml, sql/service/src/test/scala/org/apache/spark/sql/service/ui/SparkThriftServerPageSuite.scala
=> [BACKPORT][SPARK-29725][SQL][TESTS] Add ThriftServerPageSuite

sql/service/src/test/scala/org/apache/spark/sql/service/ThriftServerQueryTestSuite.scala
=> [SPARK-28527][FOLLOW-UP][SQL][TEST] Add guides for ThriftServerQueryTestSuite

sql/service/src/main/scala/org/apache/spark/sql/service/ui/ThriftServerPage.scala, sql/service/src/main/scala/org/apache/spark/sql/service/ui/ToolTips.scala
=> [SPARK-29456][WEBUI] Improve tooltip for Session Statistics Table column in JDBC/ODBC Server Tab

sql/service/src/main/java/org/apache/spark/sql/service/cli/Type.java, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/SparkExecuteStatementOperation.scala
This PR remove `CalendarIntervalType` from `Type.java`.
=> Revert Interval support

sql/service/src/main/java/org/apache/spark/sql/service/cli/session/ServiceSessionImpl.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/session/SessionManager.java, sql/service/src/main/scala/org/apache/spark/sql/service/internal/ServiceConf.scala
=> hiverc -> sparkrc

dev/create-release/release-build.sh
=> Release hive profile should not with -Pspark-thriftserver

sql/service/src/main/java/org/apache/spark/sql/service/cli/processor/ISparkFileProcessor.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/processor/SparkFileProcessor.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/session/ServiceSessionImpl.java
=> Change package name file -> processor 

sql/service/src/main/java/org/apache/spark/sql/service/auth/KerberosSaslHelper.java
=> BACKPORT HIVE-15177

dev/sparktestsupport/modules.py
=> Fix module id

launcher/src/main/java/org/apache/spark/launcher/AbstractCommandBuilder.java, project/SparkBuild.scala
build other module need `spark-thriftserver`, remove wrong old dep
=> Update mima setting

sql/service/src/main/java/org/apache/spark/sql/service/auth/SparkAuthFactory.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/thrift/ThriftCLIService.java
=> support both hive and spark proxy

project/SparkBuild.scala, sql/jdbc/src/test/scala/org/apache/spark/sql/jdbc/ThriftServerWithSparkContextSuite.scala, sql/service/pom.xml, sql/service/src/main/java/org/apache/spark/sql/service/AbstractService.java, sql/service/src/main/java/org/apache/spark/sql/service/BreakableService.java, sql/service/src/main/java/org/apache/spark/sql/service/CompositeService.java, sql/service/src/main/java/org/apache/spark/sql/service/FilterService.java, sql/service/src/main/java/org/apache/spark/sql/service/Service.java, sql/service/src/main/java/org/apache/spark/sql/service/ServiceOperations.java, sql/service/src/main/java/org/apache/spark/sql/service/auth/AuthenticationProviderFactory.java, sql/service/src/main/java/org/apache/spark/sql/service/auth/CustomAuthenticationProviderImpl.java, sql/service/src/main/java/org/apache/spark/sql/service/auth/LdapAuthenticationProviderImpl.java, sql/service/src/main/java/org/apache/spark/sql/service/auth/PamAuthenticationProviderImpl.java, sql/service/src/main/java/org/apache/spark/sql/service/auth/SparkAuthFactory.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/CLIService.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/operation/Operation.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/operation/OperationLog.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/session/ServiceSessionBase.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/session/ServiceSessionImpl.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/session/SessionManager.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/thrift/EmbeddedThriftBinaryCLIService.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/thrift/ThriftBinaryCLIService.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/thrift/ThriftCLIService.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/thrift/ThriftHttpCLIService.java, sql/service/src/main/java/org/apache/spark/sql/service/cli/thrift/ThriftHttpServlet.java, sql/service/src/main/scala/org/apache/spark/sql/service/SparkThriftServer.scala, sql/service/src/main/scala/org/apache/spark/sql/service/cli/operation/OperationManager.scala, sql/service/src/test/scala/org/apache/spark/sql/service/ThriftServerQueryTestSuite.scala
We can remove `SparkSQLEnv` after this PR.
=> Replace SQLConf with SparkConf
